name: Publish to Heroku

on:
  push:
    branches: [master]

env:
  APP_NAME: faucet-liquid

jobs:
  push-heroku:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Login to Heroku Container registry
        run: heroku container:login

      - name: Build and push
        run: |
          heroku container:push -a $APP_NAME web 
          heroku container:release -a $APP_NAME web
